### ISSUE TITLE
discourse follow notifies on all posts, not just new topics

### ISSUE THREAD

**Issue by bethaitman** [discourse/discourse-slack-official#4]
Using `/discourse follow all` in a channel is sending notifications about all new posts, including replies to topics, when it should only send notifications about new topics. 

I originally set it to `/discourse watch all` in the channel, and then changed it, so I don't know if it hasn't picked up the change in settings, or if it always sends notifications about everything. (If it helps, `/discourse status` says `is following ​*all categories*​`.

I've also tried muting the channel and setting it back to follow, with no success.

**Comment by nicksahler** [comment]
Ah - this wasn't a problem before. I'll look into this bug now and post back. Thank you!

**Comment by nicksahler** [comment]
Fixed a la 2a84a2f

**Comment by bethaitman** [comment]
Awesome! Thanks so much for fixing it so speedily :) Do we need to do anything to update Discourse/the slack integration that's live at the moment?

**Comment by nicksahler** [comment]
./launcher rebuild app should do the trick if you're self-hosting. If we're hosting you, it should update on its own soon enough.

**Comment by bethaitman** [comment]
You're hosting us, so that should all be fine. Thanks!

**Comment by bethaitman** [comment]
Hey - is there any way we can check if we've got the update yet? It still doesn't seem to be working for us.
